"""Caldera REST API クライアント。

MITRE Caldera に Adversary プロファイルを生成・同期する。

必要な環境変数:
  CALDERA_URL:     Caldera サーバーの URL（例: http://caldera.internal:8888）
  CALDERA_API_KEY: Caldera REST API Key（UI の Settings で確認可能）
"""

from __future__ import annotations

from typing import Any

import structlog

try:
    import requests
except ImportError:
    requests = None  # type: ignore[assignment]

logger = structlog.get_logger(__name__)

_ADVERSARY_ENDPOINT = "/api/v2/adversaries"
_ABILITY_ENDPOINT = "/api/v2/abilities"


def get_adversaries(caldera_url: str, api_key: str) -> list[dict[str, Any]]:
    """Caldera に登録済みの Adversary プロファイル一覧を返す。"""
    if requests is None:
        logger.error("caldera_client_failed", reason="requests not installed")
        return []

    try:
        resp = requests.get(
            f"{caldera_url.rstrip('/')}{_ADVERSARY_ENDPOINT}",
            headers={"KEY": api_key},
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()
    except Exception as exc:
        logger.error("caldera_get_adversaries_failed", error=str(exc))
        return []


def create_adversary(
    caldera_url: str,
    api_key: str,
    name: str,
    description: str,
    atomic_ordering: list[str],
) -> dict[str, Any] | None:
    """Caldera に Adversary プロファイルを新規作成する。

    Args:
        caldera_url: Caldera サーバーの URL
        api_key: REST API キー
        name: プロファイル名
        description: プロファイルの説明
        atomic_ordering: Ability ID のリスト（実行順序）

    Returns:
        作成された Adversary の dict、失敗時は None
    """
    if requests is None:
        logger.error("caldera_client_failed", reason="requests not installed")
        return None

    payload = {
        "name": name,
        "description": description,
        "atomic_ordering": atomic_ordering,
        "objective": "495a9828-cab1-44dd-a0ca-66e58177d8cc",  # default objective
    }

    try:
        resp = requests.post(
            f"{caldera_url.rstrip('/')}{_ADVERSARY_ENDPOINT}",
            json=payload,
            headers={"KEY": api_key, "Content-Type": "application/json"},
            timeout=15,
        )
        resp.raise_for_status()
        result = resp.json()
        logger.info("caldera_adversary_created", name=name, adversary_id=result.get("id"))
        return result
    except Exception as exc:
        logger.error("caldera_create_adversary_failed", name=name, error=str(exc))
        return None


def update_adversary(
    caldera_url: str,
    api_key: str,
    adversary_id: str,
    atomic_ordering: list[str],
) -> bool:
    """既存 Adversary プロファイルの Ability リストを更新する。"""
    if requests is None:
        return False

    try:
        resp = requests.patch(
            f"{caldera_url.rstrip('/')}{_ADVERSARY_ENDPOINT}/{adversary_id}",
            json={"atomic_ordering": atomic_ordering},
            headers={"KEY": api_key, "Content-Type": "application/json"},
            timeout=15,
        )
        resp.raise_for_status()
        logger.info("caldera_adversary_updated", adversary_id=adversary_id)
        return True
    except Exception as exc:
        logger.error("caldera_update_adversary_failed", adversary_id=adversary_id, error=str(exc))
        return False


def sync_actor_ttps(
    caldera_url: str,
    api_key: str,
    actor_stix_id: str,
    ttp_rows: list[dict[str, Any]],
) -> dict[str, Any]:
    """アクターの TTP フローを Caldera Adversary プロファイルとして同期する。

    同名の Adversary が既存の場合は Ability リストを更新する。
    存在しない場合は新規作成する。

    Args:
        caldera_url: Caldera サーバーの URL
        api_key: REST API キー
        actor_stix_id: ThreatActor の STIX ID
        ttp_rows: find_actor_ttps() の返り値（src/dst TTP ペア）

    Returns:
        {
          "action": "created" | "updated" | "skipped",
          "adversary_id": "...",
          "ability_count": N,
        }
    """
    # TTP STIX ID を重複排除しつつ順序を保持
    seen: set[str] = set()
    ordered_ttps: list[str] = []
    for row in ttp_rows:
        for key in ("src_ttp_stix_id", "dst_ttp_stix_id"):
            stix_id = row.get(key, "")
            if stix_id and stix_id not in seen:
                seen.add(stix_id)
                ordered_ttps.append(stix_id)

    # Caldera では Ability ID が必要だが、STIX ID を暫定で使用
    # 実運用では TTP→Ability のマッピングテーブルが必要
    ability_ids = ordered_ttps

    profile_name = f"SAGE-{actor_stix_id}"
    description = f"Auto-generated by SAGE from {actor_stix_id}"

    existing = get_adversaries(caldera_url, api_key)
    for adv in existing:
        if adv.get("name") == profile_name:
            adv_id = adv["adversary_id"]
            updated = update_adversary(caldera_url, api_key, adv_id, ability_ids)
            return {
                "action": "updated" if updated else "skipped",
                "adversary_id": adv_id,
                "ability_count": len(ability_ids),
            }

    created = create_adversary(
        caldera_url, api_key, profile_name, description, ability_ids
    )
    if created:
        return {
            "action": "created",
            "adversary_id": created.get("adversary_id", ""),
            "ability_count": len(ability_ids),
        }

    return {"action": "skipped", "adversary_id": "", "ability_count": 0}
