"""MITRE Caldera REST API client.

Generates and synchronizes Adversary profiles in MITRE Caldera.

Required environment variables:
  CALDERA_URL:     Caldera server URL (e.g. http://caldera.internal:8888)
  CALDERA_API_KEY: Caldera REST API key (visible in the Caldera UI under Settings)
"""

from __future__ import annotations

from typing import Any

import structlog

try:
    import requests
except ImportError:
    requests = None  # type: ignore[assignment]

logger = structlog.get_logger(__name__)

_ADVERSARY_ENDPOINT = "/api/v2/adversaries"
_ABILITY_ENDPOINT = "/api/v2/abilities"


def get_adversaries(caldera_url: str, api_key: str) -> list[dict[str, Any]]:
    """Return the list of Adversary profiles registered in Caldera."""
    if requests is None:
        logger.error("caldera_client_failed", reason="requests not installed")
        return []

    try:
        resp = requests.get(
            f"{caldera_url.rstrip('/')}{_ADVERSARY_ENDPOINT}",
            headers={"KEY": api_key},
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()
    except Exception as exc:
        logger.error("caldera_get_adversaries_failed", error=str(exc))
        return []


def create_adversary(
    caldera_url: str,
    api_key: str,
    name: str,
    description: str,
    atomic_ordering: list[str],
) -> dict[str, Any] | None:
    """Create a new Adversary profile in Caldera.

    Args:
        caldera_url: Caldera server URL
        api_key: REST API key
        name: Profile name
        description: Profile description
        atomic_ordering: List of Ability IDs in execution order

    Returns:
        The created Adversary dict, or None on failure
    """
    if requests is None:
        logger.error("caldera_client_failed", reason="requests not installed")
        return None

    payload = {
        "name": name,
        "description": description,
        "atomic_ordering": atomic_ordering,
        "objective": "495a9828-cab1-44dd-a0ca-66e58177d8cc",  # default objective
    }

    try:
        resp = requests.post(
            f"{caldera_url.rstrip('/')}{_ADVERSARY_ENDPOINT}",
            json=payload,
            headers={"KEY": api_key, "Content-Type": "application/json"},
            timeout=15,
        )
        resp.raise_for_status()
        result = resp.json()
        logger.info("caldera_adversary_created", name=name, adversary_id=result.get("id"))
        return result
    except Exception as exc:
        logger.error("caldera_create_adversary_failed", name=name, error=str(exc))
        return None


def update_adversary(
    caldera_url: str,
    api_key: str,
    adversary_id: str,
    atomic_ordering: list[str],
) -> bool:
    """Update the Ability list of an existing Adversary profile."""
    if requests is None:
        return False

    try:
        resp = requests.patch(
            f"{caldera_url.rstrip('/')}{_ADVERSARY_ENDPOINT}/{adversary_id}",
            json={"atomic_ordering": atomic_ordering},
            headers={"KEY": api_key, "Content-Type": "application/json"},
            timeout=15,
        )
        resp.raise_for_status()
        logger.info("caldera_adversary_updated", adversary_id=adversary_id)
        return True
    except Exception as exc:
        logger.error("caldera_update_adversary_failed", adversary_id=adversary_id, error=str(exc))
        return False


def sync_actor_ttps(
    caldera_url: str,
    api_key: str,
    actor_stix_id: str,
    ttp_rows: list[dict[str, Any]],
) -> dict[str, Any]:
    """Sync an actor's TTP flow as a Caldera Adversary profile.

    Updates the Ability list if a profile with the same name already exists.
    Creates a new profile if none exists.

    Args:
        caldera_url: Caldera server URL
        api_key: REST API key
        actor_stix_id: ThreatActor STIX ID
        ttp_rows: Return value of find_actor_ttps() (src/dst TTP pairs)

    Returns:
        {
          "action": "created" | "updated" | "skipped",
          "adversary_id": "...",
          "ability_count": N,
        }
    """
    # Deduplicate TTP STIX IDs while preserving order
    seen: set[str] = set()
    ordered_ttps: list[str] = []
    for row in ttp_rows:
        for key in ("src_ttp_stix_id", "dst_ttp_stix_id"):
            stix_id = row.get(key, "")
            if stix_id and stix_id not in seen:
                seen.add(stix_id)
                ordered_ttps.append(stix_id)

    # Caldera requires Ability IDs; STIX IDs are used as a placeholder here.
    # A TTP→Ability mapping table is required for production use.
    ability_ids = ordered_ttps

    profile_name = f"SAGE-{actor_stix_id}"
    description = f"Auto-generated by SAGE from {actor_stix_id}"

    existing = get_adversaries(caldera_url, api_key)
    for adv in existing:
        if adv.get("name") == profile_name:
            adv_id = adv["adversary_id"]
            updated = update_adversary(caldera_url, api_key, adv_id, ability_ids)
            return {
                "action": "updated" if updated else "skipped",
                "adversary_id": adv_id,
                "ability_count": len(ability_ids),
            }

    created = create_adversary(caldera_url, api_key, profile_name, description, ability_ids)
    if created:
        return {
            "action": "created",
            "adversary_id": created.get("adversary_id", ""),
            "ability_count": len(ability_ids),
        }

    return {"action": "skipped", "adversary_id": "", "ability_count": 0}
